# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Aram Bhusal
tagline:          The personal website of Aram Bhusal
url:              http://aram.io
paginate:         1
baseurl:          /
author:
  name:           Aram
  url:            https://twitter.com/phoenixwizard

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
