# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Aram Bhusal
tagline:          'code, rails, ruby, python, NLP, stories, poetry, fiction'
url:              http://aram.io
paginate:         1
baseurl:         aram.io/

author:
  name:           Aram
  url:            https://twitter.com/phoenixwizard

# Custom vars
version:          1.0.0
github:
  repo:           github.com/phoenixwizard/aram

pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

gems:
  - jekyll-redirect-from